<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>CreateUserReply</code>
 */
class CreateUserReply extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.User User = 1;</code>
     */
    protected $User = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \User $User
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\User::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.User User = 1;</code>
     * @return \User|null
     */
    public function getUser()
    {
        return isset($this->User) ? $this->User : null;
    }

    public function hasUser()
    {
        return isset($this->User);
    }

    public function clearUser()
    {
        unset($this->User);
    }

    /**
     * Generated from protobuf field <code>.User User = 1;</code>
     * @param \User $var
     * @return $this
     */
    public function setUser($var)
    {
        GPBUtil::checkMessage($var, \User::class);
        $this->User = $var;

        return $this;
    }

}

