<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: brand.proto

namespace Api\Brand\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>api.brand.v1.DeleteBrandReply</code>
 */
class DeleteBrandReply extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Brand::initOnce();
        parent::__construct($data);
    }

}

